// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"github.com/bilibili/kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// ErrCode ecode
var (
	ParameterNull = ecode.New(1)
	LogicError    = ecode.New(2)
)
