// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ErrCode int32

const (
	// 成功
	ErrCode_Success ErrCode = 0
	// 参数为空
	ErrCode_ParameterNull ErrCode = 1
	// 逻辑错误
	ErrCode_LogicError ErrCode = 2
)

var ErrCode_name = map[int32]string{
	0: "Success",
	1: "ParameterNull",
	2: "LogicError",
}

var ErrCode_value = map[string]int32{
	"Success":       0,
	"ParameterNull": 1,
	"LogicError":    2,
}

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (x *ErrCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrCode_value, data, "ErrCode")
	if err != nil {
		return err
	}
	*x = ErrCode(value)
	return nil
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type ReceiveStatus int32

const (
	// 成功
	ReceiveStatus_ReceiveSuccess ReceiveStatus = 0
	// 失败
	ReceiveStatus_ReceiveFail ReceiveStatus = 1
)

var ReceiveStatus_name = map[int32]string{
	0: "ReceiveSuccess",
	1: "ReceiveFail",
}

var ReceiveStatus_value = map[string]int32{
	"ReceiveSuccess": 0,
	"ReceiveFail":    1,
}

func (x ReceiveStatus) Enum() *ReceiveStatus {
	p := new(ReceiveStatus)
	*p = x
	return p
}

func (x ReceiveStatus) String() string {
	return proto.EnumName(ReceiveStatus_name, int32(x))
}

func (x *ReceiveStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReceiveStatus_value, data, "ReceiveStatus")
	if err != nil {
		return err
	}
	*x = ReceiveStatus(value)
	return nil
}

func (ReceiveStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

type ReceiveAllReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveAllReq) Reset()         { *m = ReceiveAllReq{} }
func (m *ReceiveAllReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveAllReq) ProtoMessage()    {}
func (*ReceiveAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *ReceiveAllReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReceiveAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReceiveAllReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReceiveAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveAllReq.Merge(m, src)
}
func (m *ReceiveAllReq) XXX_Size() int {
	return m.Size()
}
func (m *ReceiveAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveAllReq proto.InternalMessageInfo

type ReceiveInfo struct {
	// id
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// 结果
	Status               *ReceiveStatus `protobuf:"varint,2,opt,name=status,enum=api.ReceiveStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReceiveInfo) Reset()         { *m = ReceiveInfo{} }
func (m *ReceiveInfo) String() string { return proto.CompactTextString(m) }
func (*ReceiveInfo) ProtoMessage()    {}
func (*ReceiveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *ReceiveInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReceiveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReceiveInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReceiveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveInfo.Merge(m, src)
}
func (m *ReceiveInfo) XXX_Size() int {
	return m.Size()
}
func (m *ReceiveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveInfo proto.InternalMessageInfo

func (m *ReceiveInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ReceiveInfo) GetStatus() ReceiveStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ReceiveStatus_ReceiveSuccess
}

type ReceiveRsp struct {
	// 领取结果
	ReceiveList          []*ReceiveInfo `protobuf:"bytes,1,rep,name=receiveList" json:"receiveList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReceiveRsp) Reset()         { *m = ReceiveRsp{} }
func (m *ReceiveRsp) String() string { return proto.CompactTextString(m) }
func (*ReceiveRsp) ProtoMessage()    {}
func (*ReceiveRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *ReceiveRsp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReceiveRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReceiveRsp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReceiveRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveRsp.Merge(m, src)
}
func (m *ReceiveRsp) XXX_Size() int {
	return m.Size()
}
func (m *ReceiveRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveRsp proto.InternalMessageInfo

func (m *ReceiveRsp) GetReceiveList() []*ReceiveInfo {
	if m != nil {
		return m.ReceiveList
	}
	return nil
}

type ReceiveByIDReq struct {
	// id
	Id                   []string `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveByIDReq) Reset()         { *m = ReceiveByIDReq{} }
func (m *ReceiveByIDReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveByIDReq) ProtoMessage()    {}
func (*ReceiveByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}
func (m *ReceiveByIDReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReceiveByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReceiveByIDReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReceiveByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveByIDReq.Merge(m, src)
}
func (m *ReceiveByIDReq) XXX_Size() int {
	return m.Size()
}
func (m *ReceiveByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveByIDReq proto.InternalMessageInfo

func (m *ReceiveByIDReq) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterEnum("api.ReceiveStatus", ReceiveStatus_name, ReceiveStatus_value)
	proto.RegisterType((*ReceiveAllReq)(nil), "api.ReceiveAllReq")
	proto.RegisterType((*ReceiveInfo)(nil), "api.ReceiveInfo")
	proto.RegisterType((*ReceiveRsp)(nil), "api.ReceiveRsp")
	proto.RegisterType((*ReceiveByIDReq)(nil), "api.ReceiveByIDReq")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0xcf, 0x6a, 0xe2, 0x40,
	0x18, 0xdf, 0x89, 0xa0, 0xf8, 0x65, 0x8d, 0xd9, 0x6f, 0x65, 0x11, 0x11, 0x09, 0x39, 0x89, 0x07,
	0x85, 0xb0, 0x97, 0xbd, 0xad, 0xba, 0x2e, 0x08, 0xb6, 0xb4, 0xe3, 0x03, 0xc8, 0x34, 0x99, 0xca,
	0xc0, 0x34, 0x13, 0x67, 0x92, 0x82, 0xd7, 0xbe, 0x42, 0xdf, 0xa2, 0x4f, 0xd2, 0x63, 0xa1, 0x2f,
	0x50, 0xa4, 0x0f, 0x52, 0x34, 0x21, 0x4d, 0xdb, 0xe3, 0xcc, 0xf7, 0xfb, 0x0f, 0x4d, 0x96, 0x88,
	0x71, 0xa2, 0x55, 0xaa, 0xb0, 0xc6, 0x12, 0xd1, 0xeb, 0x6f, 0x95, 0xda, 0x4a, 0x3e, 0x61, 0x89,
	0x98, 0xb0, 0x38, 0x56, 0x29, 0x4b, 0x85, 0x8a, 0x4d, 0x0e, 0xf1, 0xdb, 0xd0, 0xa2, 0x3c, 0xe4,
	0xe2, 0x96, 0x4f, 0xa5, 0xa4, 0x7c, 0xe7, 0x2f, 0xc1, 0x2e, 0x3e, 0x96, 0xf1, 0xb5, 0x42, 0x07,
	0x2c, 0x11, 0x75, 0x89, 0x47, 0x86, 0x4d, 0x6a, 0x89, 0x08, 0x47, 0x50, 0x37, 0x29, 0x4b, 0x33,
	0xd3, 0xb5, 0x3c, 0x32, 0x74, 0x02, 0x1c, 0x1f, 0xed, 0x0a, 0xc6, 0xfa, 0x74, 0xa1, 0x05, 0xc2,
	0xff, 0x0b, 0x50, 0x1c, 0xa8, 0x49, 0x30, 0x00, 0x5b, 0xe7, 0xaf, 0x95, 0x30, 0x69, 0x97, 0x78,
	0xb5, 0xa1, 0x1d, 0xb8, 0x55, 0xfa, 0xd1, 0x90, 0x56, 0x41, 0xbe, 0x07, 0x4e, 0x71, 0x9b, 0xed,
	0x97, 0xff, 0x28, 0xdf, 0x95, 0x79, 0x6a, 0x79, 0x9e, 0xd1, 0x1f, 0x68, 0x2c, 0xb4, 0x9e, 0xab,
	0x88, 0xa3, 0x0d, 0x8d, 0x75, 0x16, 0x86, 0xdc, 0x18, 0xf7, 0x1b, 0xfe, 0x80, 0xd6, 0x05, 0xd3,
	0xec, 0x86, 0xa7, 0x5c, 0x9f, 0x67, 0x52, 0xba, 0x04, 0x1d, 0x80, 0x95, 0xda, 0x8a, 0x70, 0xa1,
	0xb5, 0xd2, 0xae, 0x35, 0xfa, 0x5d, 0x56, 0xcf, 0x73, 0x23, 0x96, 0x6e, 0xef, 0x3a, 0xed, 0x72,
	0x8e, 0xff, 0x4c, 0x48, 0x97, 0x04, 0x0f, 0x04, 0xea, 0x73, 0x95, 0x25, 0x2a, 0xc6, 0xb3, 0xb2,
	0xdf, 0x54, 0x4a, 0xfc, 0xb0, 0x44, 0x3e, 0x66, 0xaf, 0x5d, 0xfd, 0xa3, 0x26, 0xf1, 0x7b, 0x77,
	0xcf, 0xaf, 0xf7, 0x56, 0xc7, 0xc7, 0xf0, 0x24, 0x31, 0x29, 0xca, 0x6e, 0x98, 0x94, 0x78, 0x59,
	0x5a, 0x1d, 0xcb, 0xe2, 0xcf, 0x2a, 0xb7, 0xa8, 0xff, 0x55, 0xb0, 0x7f, 0x12, 0xfc, 0xe5, 0x77,
	0x3e, 0x09, 0x5e, 0xed, 0x37, 0x22, 0x9a, 0x7d, 0x7f, 0x3c, 0x0c, 0xc8, 0xd3, 0x61, 0x40, 0x5e,
	0x0e, 0x03, 0xf2, 0x16, 0x00, 0x00, 0xff, 0xff, 0x13, 0xd1, 0xd5, 0xb1, 0x1a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CouponClient is the client API for Coupon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CouponClient interface {
	// 领取所有
	ReceiveAll(ctx context.Context, in *ReceiveAllReq, opts ...grpc.CallOption) (*ReceiveRsp, error)
	// 根据id领取
	ReceiveByID(ctx context.Context, in *ReceiveByIDReq, opts ...grpc.CallOption) (*ReceiveRsp, error)
}

type couponClient struct {
	cc *grpc.ClientConn
}

func NewCouponClient(cc *grpc.ClientConn) CouponClient {
	return &couponClient{cc}
}

func (c *couponClient) ReceiveAll(ctx context.Context, in *ReceiveAllReq, opts ...grpc.CallOption) (*ReceiveRsp, error) {
	out := new(ReceiveRsp)
	err := c.cc.Invoke(ctx, "/api.Coupon/ReceiveAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) ReceiveByID(ctx context.Context, in *ReceiveByIDReq, opts ...grpc.CallOption) (*ReceiveRsp, error) {
	out := new(ReceiveRsp)
	err := c.cc.Invoke(ctx, "/api.Coupon/ReceiveByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServer is the server API for Coupon service.
type CouponServer interface {
	// 领取所有
	ReceiveAll(context.Context, *ReceiveAllReq) (*ReceiveRsp, error)
	// 根据id领取
	ReceiveByID(context.Context, *ReceiveByIDReq) (*ReceiveRsp, error)
}

// UnimplementedCouponServer can be embedded to have forward compatible implementations.
type UnimplementedCouponServer struct {
}

func (*UnimplementedCouponServer) ReceiveAll(ctx context.Context, req *ReceiveAllReq) (*ReceiveRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveAll not implemented")
}
func (*UnimplementedCouponServer) ReceiveByID(ctx context.Context, req *ReceiveByIDReq) (*ReceiveRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveByID not implemented")
}

func RegisterCouponServer(s *grpc.Server, srv CouponServer) {
	s.RegisterService(&_Coupon_serviceDesc, srv)
}

func _Coupon_ReceiveAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).ReceiveAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Coupon/ReceiveAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).ReceiveAll(ctx, req.(*ReceiveAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_ReceiveByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).ReceiveByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Coupon/ReceiveByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).ReceiveByID(ctx, req.(*ReceiveByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coupon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Coupon",
	HandlerType: (*CouponServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveAll",
			Handler:    _Coupon_ReceiveAll_Handler,
		},
		{
			MethodName: "ReceiveByID",
			Handler:    _Coupon_ReceiveByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func (m *ReceiveAllReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReceiveAllReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReceiveAllReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *ReceiveInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReceiveInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReceiveInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Status != nil {
		i = encodeVarintApi(dAtA, i, uint64(*m.Status))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != nil {
		i -= len(*m.Id)
		copy(dAtA[i:], *m.Id)
		i = encodeVarintApi(dAtA, i, uint64(len(*m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReceiveRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReceiveRsp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReceiveRsp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ReceiveList) > 0 {
		for iNdEx := len(m.ReceiveList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReceiveList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ReceiveByIDReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReceiveByIDReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReceiveByIDReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Id) > 0 {
		for iNdEx := len(m.Id) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Id[iNdEx])
			copy(dAtA[i:], m.Id[iNdEx])
			i = encodeVarintApi(dAtA, i, uint64(len(m.Id[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReceiveAllReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReceiveInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != nil {
		l = len(*m.Id)
		n += 1 + l + sovApi(uint64(l))
	}
	if m.Status != nil {
		n += 1 + sovApi(uint64(*m.Status))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReceiveRsp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ReceiveList) > 0 {
		for _, e := range m.ReceiveList {
			l = e.Size()
			n += 1 + l + sovApi(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReceiveByIDReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Id) > 0 {
		for _, s := range m.Id {
			l = len(s)
			n += 1 + l + sovApi(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReceiveAllReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReceiveAllReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReceiveAllReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReceiveInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReceiveInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReceiveInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Id = &s
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v ReceiveStatus
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= ReceiveStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = &v
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReceiveRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReceiveRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReceiveRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiveList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiveList = append(m.ReceiveList, &ReceiveInfo{})
			if err := m.ReceiveList[len(m.ReceiveList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReceiveByIDReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReceiveByIDReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReceiveByIDReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApi = fmt.Errorf("proto: unexpected end of group")
)
